{{ if and .Values.registry .Values.username .Values.password }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" .Values }}
{{ end }}
