apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
data:
  ENTRYPOINT_DEBUG: ""
  RSPAMD_PASSWORD: "{{ .Values.rspamd.password }}"
  WORKER_PROXY_PORT: "{{ index .Values.port 0 }}"
  WORKER_CONTROLLER_PORT: "{{ index .Values.port 2 }}"
